tz 15
Vitalya1991/java-shareit pull request #3
Opened 2023-06-06 18:15 UTC by Vitalya1991

2023-06-07 07:41 UTC, LexLippi requested changes
Привет!

Отличная работа!

Есть пара замечаний, которые необходимо исправить!

Желаю удачи!

2023-06-07 07:41 UTC, LexLippi commented on src/test/java/ru/practicum/shareit/user/service/UserServiceImplTest.java
> +    private UserStorageImpl userStorageImpl;
В тестах нет необходимости в модификаторах доступа

2023-06-07 07:41 UTC, LexLippi commented on src/test/java/ru/practicum/shareit/user/dto/UserMapperTest.java
> +    private User createUser() {
аналогично про модификатор

2023-06-07 07:41 UTC, LexLippi commented on src/test/java/ru/practicum/shareit/user/controller/UserControllerTest.java
> +    private UserService userService;
модификаторы

2023-06-07 07:41 UTC, LexLippi commented on src/main/resources/application.properties
> +#
удаляем если не нужно

2023-06-07 07:41 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                                            @RequestParam(required = false, defaultValue = "ALL") String state) {
`defaultValue` уже включает в себя `required = false`, так что в этом нет необходимости

2023-06-07 07:41 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +            @RequestParam(required = false, defaultValue = "ALL") String state) {
Аналогично тому, что выше

2023-06-07 07:41 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new RuntimeException("Такого user id не существует");
1. Причем здесь `userId`
2. Можно в контроллер добавить аннотацию `PositiveOrZero`

2023-06-07 07:41 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new RuntimeException("Такого user id не существует");
Аналогично тому, что выше

2023-06-07 10:47 UTC, Vitalya1991 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new RuntimeException("Такого user id не существует");
там есть аннотация в контроллере это не помогает(

2023-06-08 10:59 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2023-06-15 17:16 UTC, merged